# CS 6470 A0 — Environment & Python refresh

**20 points** · Module 1 · Applied Artificial Intelligence on-ramp (not an MCS NumPy / linear-algebra weeder).

**Before you submit:** rename this file to `CS6470_A0_LastName_FirstName.ipynb`.

Open in [Google Colab](https://colab.research.google.com/) (default) or local Jupyter (Python 3.10+). Run every code cell from top to bottom. The default path already works with the public seaborn `tips` table — you do not have to invent a dataset.

Lines marked `# TODO` (and the memo prompts in Task 6) are the only places you need to edit. Everything else is ready to run.

| What we score | Points |
|---|---|
| Environment runs (imports + CSV load) | 8 |
| Honest split + DummyClassifier | 7 |
| Half-page context note | 5 |

This assignment is **not** 20 from-scratch NumPy, calculus, or linear-algebra tasks. Finishing INFO 6200 is not required to continue.

## Task 1 of 6 — Import pandas, sklearn, and matplotlib

Print versions so we can see the environment is ready. You should not need to change this cell.

In [2]:
# Ready to run — only edit if an import fails and you add a Colab !pip line.
import os
import certifi
import pandas as pd
import sklearn
import matplotlib
import sys
import ssl

os.environ["SSL_CERT_FILE"] = certifi.where()

print("pandas", pd.__version__)
print("sklearn", sklearn.__version__)
print("matplotlib", matplotlib.__version__)
print("Python:", sys.executable)
print("SSL_CERT_FILE:", os.environ.get("SSL_CERT_FILE"))
print("Certificate:", ssl.get_default_verify_paths().cafile)
print(ssl.get_default_verify_paths().cafile)
print("Certificate:", os.environ["SSL_CERT_FILE"])

pandas 2.3.3
sklearn 1.8.0
matplotlib 3.10.9
Python: /Users/mariah/Downloads/CS6470/.venv/bin/python
SSL_CERT_FILE: /Users/mariah/Downloads/CS6470/.venv/lib/python3.13/site-packages/certifi/cacert.pem
Certificate: /Users/mariah/Downloads/CS6470/.venv/lib/python3.13/site-packages/certifi/cacert.pem
/Users/mariah/Downloads/CS6470/.venv/lib/python3.13/site-packages/certifi/cacert.pem
Certificate: /Users/mariah/Downloads/CS6470/.venv/lib/python3.13/site-packages/certifi/cacert.pem

In [3]:
import requests
import certifi

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"

response = requests.get(url, verify=certifi.where())

print("Status:", response.status_code)
print(response.text[:100])

from io import StringIO

df = pd.read_csv(StringIO(response.text))

print("Loaded rows:", len(df))

df.head()

Status: 200
"total_bill","tip","sex","smoker","day","time","size"
16.99,1.01,"Female","No","Sun","Dinner",2
10.3
Loaded rows: 244

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Task 2 of 6 — Load a small CSV

Default: public seaborn `tips` table (restaurant bills). You may paste your own public CSV URL or a tiny table you created. Workplace data is **not** required.

In [7]:
# Default public CSV — this cell runs as-is.
# (optional): replace csv_url with another public CSV.
csv_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(csv_url)
print("Loaded rows:", len(df), "from", csv_url)

# (optional alternative): comment out the two lines above and load a pasted table:
#from io import StringIO
#df = pd.read_csv(StringIO("""total_bill,tip,size
#16.99,1.01,2
#10.34,1.66,3
#21.01,3.50,3
#"""))

#print(df)

Loaded rows: 244 from https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv

## Task 3 of 6 — Peek at the data

Confirm the table loaded: first rows, shape, and column names.

In [8]:
# Ready to run.
print("shape:", df.shape)
print("columns:", list(df.columns))
df.head()

shape: (244, 7)
columns: ['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Task 4 of 6 — Classification target and train/test split

Build a simple yes/no target with a **median split** on a numeric column, then call `train_test_split` with a fixed `random_state` so the split is reproducible.

In [10]:
from sklearn.model_selection import train_test_split

# (optional): if you used your own CSV, pick a numeric column for the
# median split and one or two numeric feature columns.
target_col = "tip"
feature_cols = ["total_bill", "size"]

y = (df[target_col] >= df[target_col].median()).astype(int)
X = df[feature_cols]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

print("X_train", X_train.shape, "X_test", X_test.shape)
print("class rate in y (share of 1s):", float(y.mean()))

X_train (183, 2) X_test (61, 2)
class rate in y (share of 1s): 0.5

## Task 5 of 6 — Fit DummyClassifier and print a test metric

`DummyClassifier` is a baseline: it does not learn from the features. **A high score is not the goal.** We only need proof that sklearn can fit and score on your split.

In [11]:
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score

# Ready to run.
clf = DummyClassifier(strategy="most_frequent")
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

# A high score is not the goal — this is a baseline, not a model you are trying to beat.
test_acc = accuracy_score(y_test, y_pred)
print("test accuracy (DummyClassifier, most_frequent):", test_acc)

test accuracy (DummyClassifier, most_frequent): 0.4918032786885246

## Task 6 of 6 — Context memo (½ page, 5 points)

Replace the four prompts below with your own writing. About half a page total.

### Workplace or public stand-in

I didn't use workplace data for this assignment. I ended up using the default public Seaborn tips dataset that was provided. While troubleshooting my local environment in VScode, I also briefly used a small made-up table to make sure the the virtual environment and pandas setup were working properly before returning to the tips dataset. 

### Kind of data

Each row represents one restaurant bill or dining occasion. The columns show the total bill, tip, sex of customer, smoking status, day of the week, meal time, and number of people in the party. I just used total_bill and size for this assignment as features with the tip column used to create the yes/no Boolean target.

### INFO 6200

Yes. I have completed INFO 6200, but I needed a refresher on Python because that course introduced me to the fundamentals of Python while focusing more on using AI to augment coding and develop working applications. As a result, I have less experience writing and working through Python code independently.

### One thing to explain to a non-CS manager

I would explain that we hold out a test set because if we use all our data to build a model, we don't know how well the model will perform with new information. Splitting the data gives us a way to test the model using acutal data that we didn't train it with.
 
### AI disclosure

I used ChatGPT to give me a refresher on pandas and other machine learning concepts while working through this assignment. I also used it to troubleshoot an SSL certificate error in my local Python environment. I wrote and ran all the code by myself and used AI as an explantation and troubleshooting resource. I also wrote the memo by myself.

## How to submit

1. Rename this file to `CS6470_A0_LastName_FirstName.ipynb`.
2. Confirm every code cell ran without error.
3. Upload this notebook to the **A0 — Environment & Python refresh** assignment on Canvas.

Integrity: the notebook and memo must be yours. AI may help explain an error; it may not be the submitted analysis.